sonar.projectKey=memoria-backend
sonar.projectName=MemorIA Backend
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=17
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/config/**,**/MemorIaBackendApplication.java
sonar.sourceEncoding=UTF-8
